-- Create database if not exists
CREATE DATABASE IF NOT EXISTS symposium_db;
USE symposium_db;

-- Create faculty table
CREATE TABLE IF NOT EXISTS faculty (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    contact_number VARCHAR(15) NOT NULL,
    faculty_id VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    department VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create students table
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    contact_number VARCHAR(15) NOT NULL,
    roll_number VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    seminar_topic VARCHAR(500) NOT NULL,
    seminar_link VARCHAR(500) DEFAULT NULL,
    qr_code VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create admin table for admin login
CREATE TABLE IF NOT EXISTS admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default admin user (password: admin123)
INSERT INTO admin (username, password, email) VALUES 
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin@symposium.com')
ON DUPLICATE KEY UPDATE username=username;

-- Create seminars table to store seminar topics
CREATE TABLE IF NOT EXISTS seminars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert seminar topics from the list
INSERT INTO seminars (topic, category) VALUES
('Real-Time AI in Autonomous Drones: A Case Study on Navigation and Obstacle Avoidance', 'Artificial Intelligence & Machine Learning'),
('AI-Powered Medical Diagnosis: Applications of Deep Learning in Radiology', 'Artificial Intelligence & Machine Learning'),
('Case Study on Reinforcement Learning for Robotics in Industrial Automation', 'Artificial Intelligence & Machine Learning'),
('Explainable AI (XAI): Techniques and Applications in Healthcare', 'Artificial Intelligence & Machine Learning'),
('Federated Learning in Smart Devices: Privacy-Preserving ML Applications', 'Artificial Intelligence & Machine Learning'),
('Predictive Analytics for Smart Cities: Case Study Using Big Data from Urban Sensors', 'Data Science & Big Data Analytics'),
('Real-Time Traffic Management Using Big Data Analytics: A Case Study', 'Data Science & Big Data Analytics'),
('Data Science in Agriculture: Crop Yield Prediction Using Satellite Data', 'Data Science & Big Data Analytics'),
('Big Data and Sports Analytics: Performance Optimization in Professional Leagues', 'Data Science & Big Data Analytics'),
('Case Study on Customer Behavior Prediction in E-Commerce Using Data Science', 'Data Science & Big Data Analytics'),
('AI in Cyber Threat Detection: Case Study on Anomaly Detection Systems', 'Cybersecurity'),
('Zero Trust Architecture: Implementation in Enterprise Networks', 'Cybersecurity'),
('Ransomware Detection with Machine Learning: A Case Study in Banking Sector', 'Cybersecurity'),
('Blockchain for Secure Identity Management in Government Applications', 'Cybersecurity'),
('Case Study on Social Engineering Attacks and Cyber Awareness Training', 'Cybersecurity'),
('IoT in Smart Healthcare: Real-Time Patient Monitoring Systems', 'Internet of Things'),
('Edge AI in IoT: A Case Study on Smart Traffic Systems', 'Internet of Things'),
('IoT and Blockchain Integration for Supply Chain Transparency', 'Internet of Things'),
('Case Study on IoT-Based Predictive Maintenance in Manufacturing', 'Internet of Things'),
('Smart Farming with IoT: Real-Time Monitoring and Resource Optimization', 'Internet of Things'),
('Facial Recognition for Secure Access: Ethical and Technical Case Study', 'Computer Vision'),
('Vision-Based Quality Control in Manufacturing Using Deep Learning', 'Computer Vision'),
('NLP in Legal Document Analysis: A Case Study on AI-Powered Contract Review', 'Natural Language Processing'),
('Multimodal Learning: Combining Vision and Language in Robotics', 'Natural Language Processing'),
('Transformer-Based Models in NLP: Case Study on BERT for Sentiment Analysis', 'Natural Language Processing'),
('Smart Contracts in Real Estate Transactions: A Blockchain Case Study', 'Blockchain'),
('Blockchain for Educational Credential Verification', 'Blockchain'),
('Decentralized Finance (DeFi): Case Study of Lending Protocols on Ethereum', 'Blockchain'),
('Blockchain in Food Supply Chain Traceability', 'Blockchain'),
('Tokenization of Assets: Case Study on NFTs in Digital Art', 'Blockchain'),
('Case Study on GPT-Based Chatbots for Customer Support', 'Large Language Models'),
('Deepfake Detection Using CNNs: A Case Study', 'Large Language Models'),
('LLMs for Code Generation: Applications and Limitations in Software Development', 'Large Language Models'),
('Transfer Learning with Transformers for Low-Resource Languages', 'Large Language Models'),
('Ethical Challenges of LLMs in Education: Use and Misuse Case Study', 'Large Language Models'),
('Case Study on Digital Twin Implementation in Smart Factories', 'Cyber-Physical Systems'),
('AI-Enabled Cyber-Physical Systems for Disaster Management', 'Cyber-Physical Systems'),
('Smart Grid Optimization Using Cyber-Physical Systems', 'Cyber-Physical Systems'),
('Human-Machine Interaction in Autonomous Vehicles', 'Cyber-Physical Systems'),
('Case Study on CPS in Remote Health Monitoring and Alert Systems', 'Cyber-Physical Systems'),
('Semantic Analysis in Legal Document Summarization: A Case Study Using BERT Models', 'Generative AI'),
('Generative AI for Content Creation: Case Study on Marketing Copy Generation with GPT-4', 'Generative AI'),
('Real-Time Sentiment and Semantic Analysis in E-Governance Platforms', 'Generative AI'),
('Case Study on Generative AI in Drug Discovery: From Molecule to Medicine', 'Generative AI'),
('Ethical Implications of Generative AI in Education: An Analytical Case Study', 'Generative AI'),
('Quantum Computing for Optimization Problems: Case Study in Logistics', 'Quantum Computing'),
('Neuromorphic Computing in Edge Devices: A Case Study on Energy-Efficient AI', 'Quantum Computing'),
('Quantum Machine Learning for Portfolio Management in Finance', 'Quantum Computing'),
('Simulating Brain-Inspired Architectures: Case Study on Intel\'s Loihi Chips', 'Quantum Computing'),
('Quantum Cryptography for Secure Communication in Government Systems', 'Quantum Computing'),
('Explainable AI in Autonomous Diagnosis: Case Study in Healthcare AI Transparency', 'Explainable AI'),
('Agentic AI in Personal Digital Assistants: From Passive Tools to Proactive Agents', 'Explainable AI'),
('Interpretable Models for Fraud Detection in Banking: An Explainable AI Case Study', 'Explainable AI'),
('Case Study on Agentic AI in Workplace Automation and Productivity Tools', 'Explainable AI'),
('Ethical and Legal Boundaries of Agentic AI in Decision-Making Systems', 'Explainable AI'),
('Augmented Reality in Industrial Training: A Case Study on Skill Enhancement', 'Extended Reality'),
('XR for Medical Education: A Case Study in Virtual Surgery Simulations', 'Extended Reality'),
('AR-Based Smart Navigation for Visually Impaired: Implementation & Impact', 'Extended Reality'),
('Extended Reality in Heritage Preservation: A Case Study from Cultural Tourism', 'Extended Reality'),
('Immersive Retail: Case Study on XR-Driven Virtual Shopping Experiences', 'Extended Reality'),
('IoT and AI for Sustainable Farming: Case Study on Precision Agriculture', 'Sustainable Technology'),
('Biotechnology-Enabled Crop Monitoring Using Computer Vision', 'Sustainable Technology'),
('Sustainable Computing: Green Data Centers Powered by AI and IoT', 'Sustainable Technology'),
('Case Study on AI-Driven Vertical Farming for Urban Sustainability', 'Sustainable Technology'),
('Bioinformatics and AI in Enhancing Crop Resistance: A Tech-Agriculture Case Study', 'Sustainable Technology'),
('Swarm Robotics in Disaster Response: Real-World Deployment Case Study', 'Robotics'),
('AI-Driven Autonomous Delivery Robots: A Case Study from Last-Mile Logistics', 'Robotics'),
('Self-Healing Materials in Robotics: A Case Study in Advanced Prosthetics', 'Robotics'),
('Autonomous Vehicles in Smart Cities: Integration and Impact Case Study', 'Robotics'),
('Explainable Decision-Making in Autonomous Cars: Challenges and Solutions', 'Robotics'),
('Wireless Sensor Networks in Forest Fire Detection: A Case Study', 'Wireless Sensor Networks'),
('Smart Water Management Using IoT and WSN in Urban Infrastructure', 'Wireless Sensor Networks'),
('Case Study on Real-Time Soil Health Monitoring Using WSN in Indian Farms', 'Wireless Sensor Networks'),
('Integration of WSN and AI for Wildlife Conservation and Tracking', 'Wireless Sensor Networks'),
('WSN-Based Early Warning Systems in Earthquake-Prone Regions', 'Wireless Sensor Networks'),
('Generative AI in Software Development: A Case Study on GitHub Copilot', 'Software Development'),
('Quantum Machine Learning for Pattern Recognition: A Case Study Using Qiskit', 'Software Development'),
('AI-Driven Cybersecurity: Intrusion Detection in Enterprise Networks', 'Software Development'),
('Digital Twin Technology for Smart City Infrastructure Monitoring', 'Software Development'),
('Edge AI for Real-Time Smart Surveillance Using NVIDIA Jetson Nano', 'Software Development'),
('Federated Learning in Healthcare: Diabetic Retinopathy Detection Without Data Sharing', 'Healthcare AI'),
('Blockchain for Supply Chain Transparency: Case Study of Walmart\'s Food Traceability System', 'Healthcare AI'),
('Virtual Collaboration in the Metaverse: A Case Study on Meta\'s Horizon Workrooms', 'Healthcare AI'),
('Explainable AI in FinTech: Transparent Loan Approval Systems', 'Healthcare AI'),
('Self-Healing Software Systems: Netflix\'s Approach Using Chaos Engineering', 'Healthcare AI'),
('Swarm Robotics in Agriculture: Coordinated Drone-Based Crop Monitoring', 'Healthcare AI'),
('Neuromorphic Computing for Gesture Recognition: Intel Loihi in Action', 'Healthcare AI'),
('6G Network and Tactile Internet: Remote Surgery Use Case Analysis', 'Healthcare AI'),
('AI-Based Code Generation and Debugging: A Comparison Between GPT-4 and Human Coders', 'Healthcare AI'),
('Zero Trust Security in Cloud Computing: Google\'s Beyond Corp Model', 'Healthcare AI'),
('IoT-Based Predictive Maintenance in Smart Factories', 'Healthcare AI'),
('Augmented Reality in STEM Education: Enhancing Learning Through AR Apps', 'Healthcare AI'),
('Organoid Intelligence: Bio-Computing Applications in Pattern Recognition', 'Healthcare AI'),
('AI-Powered Mental Health Chatbots: Case Study on Wysa and Woebot', 'Healthcare AI'),
('Green Computing in Cloud Infrastructure: Google\'s AI-Optimized Data Centers', 'Healthcare AI'),
('Synthetic Data Generation with Generative AI: Use Case in Autonomous Vehicle Training', 'Healthcare AI'),
('AI Ethics and Bias Mitigation: A Case Study on Hiring Algorithms', 'Healthcare AI'),
('Real-Time Language Translation Using LLMs: Meta\'s SeamlessM4T as a Case Study', 'Healthcare AI'),
('Cyber-Physical Systems in Smart Homes: Integration of AI and IoT', 'Healthcare AI'),
('Privacy-Preserving AI: Case Study on Apple\'s On-Device Machine Learning', 'Healthcare AI'),
('Designing Agentic AI Systems for Autonomous Decision-Making: Application in Multi-Agent Coordination and a Case Study using BDI Architecture', 'Agentic AI'),
('Agentic AI in Personalized Healthcare: Application in Chronic Disease Management and Case Study on Goal-Driven Virtual Health Assistants', 'Agentic AI'),
('Agentic AI for Safe Navigation in Autonomous Vehicles: Application of Intent-Aware Agents and Case Study on Urban Traffic Simulation', 'Agentic AI'),
('Agentic AI in Precision Agriculture: Application in Crop Monitoring and Case Study of Autonomous Drone Swarms Using Cognitive Agents', 'Agentic AI'),
('Agentic AI in Human-Robot Collaboration: Application in Industrial Robotics and Case Study on Intent-Driven Task Allocation in Smart Factories', 'Agentic AI'),
('Agentic AI for Context-Aware Services in Smart Cities: Application in Urban Mobility Management and Case Study on Multi-Agent Traffic Light Control', 'Agentic AI'),
('Agentic AI in Emergency Response Systems: Application in Real-Time Rescue Coordination and Case Study Using Cognitive Agents for Earthquake Scenarios', 'Agentic AI'),
('Agentic AI for Autonomous Decision-Making: Applications in Disaster Response and a Case Study on Real-Time Rescue Simulation using Cognitive Agents', 'Agentic AI'),
('AI-Powered Chatbots in Mental Health Support: Application in Cognitive Behavioral Therapy and Case Study on Woebot\'s User Interaction Patterns', 'Conversational AI'),
('Conversational Agents for Personalized Learning: Application in Adaptive Tutoring and Case Study of ChatGPT Integration in E-Learning Platforms', 'Conversational AI'),
('Intelligent Chatbots for Customer Engagement: Application in Online Retail and Case Study on Dialogflow Implementation in Myntra\'s Support System', 'Conversational AI'),
('Secure Conversational AI in Banking: Application in Fraud Detection Assistance and Case Study on HDFC Eva Chatbot Deployment', 'Conversational AI'),
('Chatbots for E-Governance: Application in Citizen Grievance Redressal and Case Study on India\'s MyGov Chatbot Performance', 'Conversational AI'),
('AI Chatbots for Talent Acquisition: Application in Automated Candidate Screening and Case Study on Paradox Olivia in Hiring Workflows', 'Conversational AI'),
('Crisis Chatbots for Emergency Communication: Application in Disaster Helplines and Case Study of WhatsApp Bots in Healthcare', 'Conversational AI'),
('Advances in Human-Computer Interface through Natural Language Processing: Application in Voice Assistants and Case Study on Amazon Alexa\'s Conversational Design', 'Human-Computer Interaction'),
('Neuroadaptive Human-Computer Interfaces: Application in Assistive Technologies and Case Study on EEG-based Cursor Control Systems', 'Human-Computer Interaction'),
('Human-Computer Interaction for Inclusive Design: Application in Assistive Input Devices and Case Study on Eye-Tracking Systems for Motor-Impaired Users', 'Human-Computer Interaction'),
('Immersive Human-Computer Interfaces: Application in AR/VR Environments and Case Study on Gesture-Based Interaction in Oculus Quest Applications', 'Human-Computer Interaction'),
('Human-Centered Interaction in Social Robotics: Application in Companion Robots and Case Study on NAO Robot in Elderly Care', 'Human-Computer Interaction'),
('Designing Adaptive Human-Computer Interfaces: Application in Multimodal Smartphone UIs and Case Study on Gboard\'s Predictive Interaction Model', 'Human-Computer Interaction'),
('Human-Computer Interaction through Wearable Devices: Application in Health Monitoring and Case Study on UX Design in Fitbit Ecosystem', 'Human-Computer Interaction'),
('CNN based Smart Surveillance System: A Smart IoT Application Post COVID-19 Era', 'Computer Vision'),
('Super-fast Refresh Holographic Display based on Liquid Crystal Films Doped with Silver Nanoparticles', 'Display Technology'),
('Design and Validation of Multifunctional Android based Smart Home Control and Monitoring System', 'Smart Home'),
('Big Data- Based Improved Data Acquisition and Storage System for Designing Industrial Data Platform', 'Big Data'),
('DEEP- HEAR: A multimodal subtitle positioning system dedicated to deaf and hearing impaired people.', 'Assistive Technology'),
('An Intelligent Agriculture Network Security System based on Private Block Chains', 'Blockchain'),
('enhanced Player Interaction using Motion Controller for First-Person Shooting Games in Virtual Reality', 'Gaming'),
('Big Data virtualization in cardiology a systematic Review and future Directions', 'Healthcare'),
('Lightweight Sharable and Traceable Secure Mobile health System', 'Healthcare'),
('SignQuiz:A Quiz based tool for Learning Finger spelled Signs in Indian sign Language Using ASLR', 'Education'),
('Green 6G Network: Architecture and Technologies', '6G Networks'),
('Intelligence Sign Prediction with Behavior Prediction for Signed Heterogeneous Information Networks.', 'Machine Learning'),
('Alphapwd: A Password Generation Strategy Based on Mnemonic Shape', 'Cybersecurity'),
('Mobile Web Augmented reality in 5G and beyond: Challenges, opportunities and future directions.', 'AR/VR'),
('Enhancing Cloud -based IOT Security through Trustworthy Cloud service: An Integration of Security and Reputation Approach', 'Cloud Security'),
('A smart Walking Stick Powered by Artificial Intelligence for the Visually Impaired.', 'Assistive Technology'),
('Fetal weight Estimation via Ultrasound Using Machine Learning', 'Healthcare AI'),
('Artificial Intelligence based mobile tracking and Antenna Pointing in Satellite Terrestrial Network.', 'Satellite Technology'),
('The (in) Security of Virtualization in Software Defined Networks.', 'Network Security'),
('A Multi-Patient Data-Driven Approach to Blood Glucose Prediction', 'Healthcare'),
('A Machine Learning Approach for Fall Detection And Daily Living Activity Recognition', 'Healthcare'),
('An Integrated Holistic Model for E health System. A National implementation approach And a new cloud based security model', 'E-Health'),
('A Hierarchical Dimension Reduction Approach for Big Data with Application to Fault Diagnostic', 'Big Data'),
('A survey of Block Chain Technology Applied to Smart Cities: Research Issues and Challenges', 'Blockchain'),
('Understanding edge computing :Engineering evolution with artificial intelligence', 'Edge Computing'),
('Cyber pulse: A Machine Learning Based Link Flooding Attack Migration System for Software Defined Networks', 'Network Security'),
('Web server log analysis for unstructured data using Apache Flume and Pig', 'Big Data'),
('Any charge: An IoT based wireless charging service for the public', 'IoT'),
('Multifactor Authentication Protocol in a Mobile environment', 'Cybersecurity'),
('Foundation and solution of modern computing paradigms cloud, IOT, Edge and Fog', 'Cloud Computing'),
('IoT-Fog based healthcare framework to identify and control hypertension attack', 'Healthcare IoT'),
('Highly secures C31 communication network Based on Block chain technology for military system', 'Military Technology'),
('A Novel Approach for Multi-Label class X-Ray classification of common Thorax Diseases', 'Medical Imaging'),
('Authentication and Verification of Social Networking Accounts using Block Chain Technology', 'Blockchain'),
('Smart farming: Agriculture\'s shift from a labor intensive to technology native industry', 'Smart Agriculture'),
('Design of Traffic Emergency Response System Based on Internet of things and Data Mining in Emergencies', 'Emergency Systems'),
('Cost-Efficient and Quality of Experience Aware Provisioning of Virtual Machines for Multiplayer Cloud Gaming in Geographically Distributed Data Centers', 'Cloud Gaming'),
('Clean Energy consumption of power systems towards smart agriculture: Roadmap, bottlenecks and technologies', 'Clean Energy'),
('Data lake lambda architecture for smart grids big data analytics', 'Smart Grids'),
('FogFlow : Easy programming of IOT services over cloud and edges for smart cities', 'Fog Computing'),
('Honey DOC: An efficient Honeypot architecture enabling all-round design', 'Cybersecurity'),
('Secured data collection with hardware-based ciphers for IOT-based Healthcare', 'Healthcare IoT'),
('Resource sharing of a computing access point for multi-user mobile loud offloading with delay constraints', 'Mobile Computing'),
('Encryption-then compression systems using grayscale based image encryption for JPEG images', 'Image Security'),
('Virtual blind road following based wearable navigation device for blind people', 'Assistive Technology'),
('Virtual Environments testing as a cloud service: A methodology for protecting & securing virtual infrastructure', 'Cloud Security'),
('A progressive web application based on micro service combining geospatial data and IOT', 'PWA'),
('A new certificates signature scheme provably secure in the standard model', 'Cryptography'),
('Robust low-cost passive UHF RFID based smart shopping trolley', 'RFID'),
('IOT based smart grids supported by intelligent edge computing', 'Smart Grids'),
('Independent mix zone for location privacy in vehicular network', 'Privacy'),
('IOT for smart precision agriculture and farming in rural areas', 'Smart Agriculture'),
('Efficient metadata management in block level CDP system for cyber security', 'Cybersecurity'),
('Traffic fingerprinting attacks on IOT using Machine Learning', 'IoT Security'),
('Integration of data mining clustering approach in personalized e-learning system', 'E-Learning'),
('Session key establishment and authentication in a smart home network using public key cryptography', 'Smart Home'),
('Image Encryption based on interleaved computer generated hologram', 'Image Security'),
('Compact base station antenna based on image theory for UWB/5G RTLS embraced smart parking of driverless car', '5G Technology'),
('A new detection and prevention system for ARP attacks using static entry', 'Network Security'),
('Full lifecycle infrastructure management system for smart cities: A narrow band IOT based platform', 'Smart Cities'),
('Accounting for label uncertainty Machine learning for detecting of acute respiratory distress syndrome', 'Healthcare AI'),
('Technology of hiding and protecting the secret image based on 2-channel deep hiding network', 'Image Security'),
('Frequent pattern mining on time and location aware air quality data', 'Data Mining'),
('Effects of virtual reality and augmented reality on induced anxiety', 'Mental Health'),
('Molecular based Nano communication network : A ring topology nano-bots for in-vivo drug delivery system', 'Nanotechnology'),
('Understanding in-app ads and detecting hidden attacks through the mobile app-web interface', 'Mobile Security'),
('Classical and quantum cryptography for image encryption and decryption', 'Cryptography'),
('A secure cloud storage framework with access control based on blockchain', 'Cloud Security'),
('Enhanced human face recognition using LBPH descriptor multi-KNN and back propagation neural network', 'Face Recognition'),
('Design and development of IOT gateway for smart building application', 'IoT'),
('An IOT enabled stroke Rehabilitation system based on smart wearable armband and machine learning', 'Healthcare IoT'),
('Blockchain powered parallel healthcare systems based on the ACP approach', 'Healthcare Blockchain'),
('IOT: Air pollution monitoring system (IOT Mobair)', 'Environmental IoT'),
('Enhanced cyber-physical security in IOT through energy auditing', 'IoT Security'),
('Detection of glaucoma using anterior segment optical coherence tomography images', 'Medical Imaging'),
('5G-QoE Modelling for ultra-HD video streaming in 5G networks', '5G Networks'),
('Privacy preserved ,provable secure, mutually authenticated key protocol for healthcare in smart city environment', 'Healthcare Security'),
('YOMO: An efficient convolution neural network for face detection', 'Face Detection'),
('Paintcopter : An autonomous UAV for Spray painting on 3D Surfaces', 'Robotics'),
('Smart health monitoring : Early prediction of heart problems through predictive analysis of ECG signals', 'Healthcare AI'),
('TCP-Drinc: Smart congestion control based on deep reinforcement learning', 'Network Optimization'),
('Electrical safety considerations in large scale electric vehicle charging stations', 'Electric Vehicles'),
('EACMS: Emergence Access Control management system for personal health record based on blockchain', 'Healthcare Blockchain'),
('QTCP: Adaptive congestion control with reinforcement learning', 'Network Optimization'),
('Designing future precision agriculture: Detection of seed germination using AI on a low-power embedded system', 'Precision Agriculture'),
('An IOT enabled smart sensing system for nitrate monitoring', 'Environmental IoT'),
('Evaluating the operational application of SMAP for global agriculture drought monitoring', 'Remote Sensing');
